# Lists
## .remove() .reverse() .sort() .pop() 
### the .sort() function sorts the list with inplace=true if in case you want to  intact the original list and want to store the sorted list somewhere else you can use sorted() function

In [ ]:
list_=list()
for i in range(10):
  list_.append(i)
print(list_)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
list_.insert(2,55)
list_

[0, 1, 55, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list_.sort()
list_

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55]

In [ ]:
list_.append(-1)
list_new=sorted(list_)
print(list_new)
print(list_)

[-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55, -1]


### if you want to add same element multiple times

In [ ]:
mylist=[0]*5
mylist

[0, 0, 0, 0, 0]

and you pretty much know slicing, right?

### how to reverse a list without using the reverse function

In [ ]:
list_[::-1]

[-1, 55, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

### how to copy list carefully??
dont use the assignment operator because in that case both the copied and original list are referring to the same list in the memory so always use copy function


In [ ]:
list_my=list_.copy()
list_my

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55, -1]

if using assignment operator to copy lists, then changing something in copied list would reflect change in the original list as well

### Three methods of  making actual copy of a list

In [ ]:
# 1.
list_1=list_[:]
# 2.
list_2=list(list_)
# 3.
list_3=list_.copy()

print(list_1,"\n",
      list_2,"\n",
      list_3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55, -1] 
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55, -1] 
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55, -1]


## **List Comprehensions**

In [ ]:
list_b=[i*2 for i in list_1]
print(list_b)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 110, -2]


In [ ]:
num1=[1,3,5,7,9]
num2=[2,4,6,8,10]
num3=[(x,y) for x in num1 for y in num2]

In [ ]:
num3

In [ ]:
names=['Ram','Rinu','Tina','Mohan']
name_havee_a=[x for x in names if 'a' in x]

In [ ]:
name_havee_a

['Ram', 'Tina', 'Mohan']

using if else in list comprehension

In [ ]:
odd_even=[str(i)+'=Even'if i%2==0 else str(i)+'=Odd' for i in range(11)]
odd_even

['0=Even',
 '1=Odd',
 '2=Even',
 '3=Odd',
 '4=Even',
 '5=Odd',
 '6=Even',
 '7=Odd',
 '8=Even',
 '9=Odd',
 '10=Even']

how to flatten list in python?


In [ ]:
list_1=[[1,2],[3,4]]
list_flat=[ num for row in list_1 for num in row]

In [ ]:
list_flat

[1, 2, 3, 4]

In [ ]:
list_1[0][1]

2

# Tuples

In [ ]:
mytup=('max')
type(mytup)

str

### it will treat it as a tring and not a tuple so here's how you fix it:

In [ ]:
mytup=('max',)
type(mytup)

tuple

### change tuple to list:

In [ ]:
tuple(list_2)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 55, -1)

### .count()

In [ ]:
mytup.count('max')

1

### .index()

In [ ]:
mytup.index("max")

0

### unpacking tuple items

In [ ]:
mutuple=[1,2,3,4,5,6,7,8]
i1,*i2,i3=mutuple
print(i1)
print(*i2)
print(i3)

1
2 3 4 5 6 7
8


### why to use tuple over list?
it is efficient and acquires less memory area

In [ ]:
import timeit
print(timeit.timeit(stmt='[0,1,2,3,4,5]',number=1000000))
print(timeit.timeit(stmt='(0,1,2,3,4,5)',number=1000000))

0.08944455699929676
0.01274865300001693


# Dictionaries

In [ ]:
mydict=dict(name='ushna',age=22)
mydict

{'age': 22, 'name': 'ushna'}

### Three ways to delete values inside dictionaries

In [ ]:
del mydict['name']

In [ ]:
mydict.pop('age')

22

In [ ]:
mydict.popitem()

('age', 22)

In [ ]:
'name' in mydict

True

### try and except

In [ ]:
try:
  print(mydict['pp'])
except:
  print('error')

error


### .values() .items() .keys()

In [ ]:
for key, value in mydict.items():
  print(key,value)

name ushna
age 22


In [ ]:
for value in mydict.values():
  print(value)

ushna
22


### updating/merging dictionaries

In [ ]:
mydict2=dict(name='khan',email='xyz')
mydict.update(mydict2)
mydict

{'age': 22, 'email': 'xyz', 'name': 'khan'}

#### dictionary values are mutable
we can use tuple in place of keys but cannot use list because lists are mmutable

In [ ]:
tuplee=(2,3,4)
myd={tuplee:'okay'}
myd

{(2, 3, 4): 'okay'}

# Sets

## sets doesnot allow duplicates

In [ ]:
myset=set('Hello')
myset

{'H', 'e', 'l', 'o'}

In [ ]:
myset=set()
myset.add(1)
myset.add(2)
myset.add(3)
myset

{1, 2, 3}

### Removing elements
.pop() .remove() .discard() .clear()

In [ ]:
myset.pop()

1

In [ ]:
myset.clear()
myset

set()

In [ ]:
myset.remove(3)

In [ ]:
myset.discard(5)

In [ ]:
myset

{1, 2}

## Unions and Intersections

In [ ]:
odd={1,3,5,7}
even={2,4,6,8}
primes={2,3,5,7}

In [ ]:
uni=odd.union(even)
uni

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
inter=odd.intersection(primes)

In [ ]:
inter

{3, 5, 7}

### set difference: return only the elements present in first set and exclude the onre that are present in the second set

In [ ]:
set1={1,2,3,4,5,6,7}
set2={5,6,7,8,9,10}
# unique elements in both the sets
set1.difference(set2)

{1, 2, 3, 4}

In [ ]:
set2.difference(set1)

{8, 9, 10}

In [ ]:
# common elements in both the sets

set1- set1.difference(set2)

{5, 6, 7}

In [ ]:
# or we have a function for that
set1.symmetric_difference(set2)

{1, 2, 3, 4, 8, 9, 10}

#### write a function to print common values in two sets

In [ ]:
def common(set1,set2):
  for i in set1:
    for j in set2:
      if i==j:
        print(i)

In [ ]:
common(set1,set2)

5
6
7


#### writing the same function using list comprehension

In [ ]:
set([i for i in set1 for j in set2 if i==j])

{5, 6, 7}

In [ ]:
set1.issubset(set2)

False

#### frozensets

In [ ]:
sets=frozenset([1,2,3,4,6])
sets

frozenset({1, 2, 3, 4, 6})

# Strings

In [ ]:
strings='Hello World'
strings.startswith('H')

True

In [ ]:
strings.endswith('d')

True

### .strip() is used to cut down the wide spaces

since strings are immutable how to replace them

In [ ]:
strings.replace("World",'Universe')

'Hello Universe'

In [ ]:
list_=strings.split()
list_

['Hello', 'World']

#### quickly joins the elements of a list

In [ ]:
str_=" ".join(list_)
str_

'Hello World'

### formatting a string

In [ ]:
name='ushna'
age=22
print("my name is {} and i am {:.2f}".format(name,age))

my name is ushna and i am 22.00


In [ ]:
print(f"my name is {name} and i am {age}")

my name is ushna and i am 22


# Collections in pyython
## 1. Counter

In [ ]:
from collections import Counter
str1='aavcfghhhhhbbbbjjj'
mycounter=Counter()
type(mycounter)

collections.Counter

### how to find unique elements in a string using counter

In [ ]:
mycounter=Counter(str1)
mycounter # returns sictionary

##---------unique values-----------
mycounter.keys()

dict_keys(['a', 'v', 'c', 'f', 'g', 'h', 'b', 'j'])

### how to see most common element in python

In [ ]:
mycounter.most_common(2)

[('h', 5), ('b', 4)]

In [ ]:
list(mycounter.elements())

## 2. Namedtuple

In [ ]:
from collections import namedtuple ## struct type
Point=namedtuple('Point','x,y')  ## will create a class point with fields x and y
pt=Point(1,3)
pt

Point(x=1, y=3)

## 3. OrderedDict

In [ ]:
from collections import OrderedDict

In [ ]:
mydict={'name':'ushna','age':22}

In [ ]:
mydict #does not retain order

{'age': 22, 'name': 'ushna'}

In [ ]:
ordered=OrderedDict()
ordered['name']='ushna'
ordered['age']=22
ordered

OrderedDict([('name', 'ushna'), ('age', 22)])

In [ ]:
ordered={}
ordered['name']='ushna'
ordered['age']=22
ordered

{'age': 22, 'name': 'ushna'}

## 4. defaultdict
use defaultdict to avoid raising key errors

In [ ]:
from collections import defaultdict
d=defaultdict(int) #or use float list etc
d['a']=1
d['b']=2
print(d['c'])

0


## 5. deque
deque is a double ended queue

In [ ]:
from collections import deque
### we can insert and remove elements from both the ends

d=deque()
d.append(0)
d.append(1)
print(d)
print(type(d))
d.appendleft(-1)
print(d)
d.pop()
print(d)
d.popleft()
print(d)

deque([0, 1])
<class 'collections.deque'>
deque([-1, 0, 1])
deque([-1, 0])
deque([0])


In [ ]:
d.extend([4,5,6])
d

deque([0, 4, 5, 6, 4, 5, 6])

In [ ]:
d.extendleft([5,9,0])

In [ ]:
d

deque([0, 9, 5, 0, 4, 5, 6, 4, 5, 6])

In [ ]:
d.rotate(1)
d

deque([6, 0, 9, 5, 0, 4, 5, 6, 4, 5])

# Itertools

In [ ]:
from itertools import product

list1=[1,2,3]
list2=[4,6,'m']

prod=product(list1,list2)
print(list(prod))

[(1, 4), (1, 6), (1, 'm'), (2, 4), (2, 6), (2, 'm'), (3, 4), (3, 6), (3, 'm')]


In [ ]:
from itertools import permutations
# to see all the different orderings
permutaion=permutations(list1)
print(permutaion)

In [ ]:
print(list(permutaion))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [ ]:
from itertools import combinations
comb=combinations(list1,2)
print(list(comb))

[(1, 2), (1, 3), (2, 3)]


In [ ]:
from itertools import accumulate
list1=[1,2,3,4,5,6]
acc=accumulate(list1)
print(list1)
print(list(acc))

# by default it will just add but we can do multiply as well

import operator
acc=accumulate(list1,func=operator.mul)
print(list(acc))   #factorial

[1, 2, 3, 4, 5, 6]
[1, 3, 6, 10, 15, 21]
[1, 2, 6, 24, 120, 720]


In [ ]:
from itertools import groupby
l1=[1,2,3,4,5,65]

def smaller_than_3(x):
  return x>3

group=groupby(l1,key=smaller_than_3)

for key, value in group:
  print(key,list(value))

False [1, 2, 3]
True [4, 5, 65]


In [ ]:
# example2------------->
l2=[{'name':'tina','age':20},{'name':'mina','age':20},{'name':'dika','age':12}]
group=groupby(l2, key= lambda x: x['age'])
for key, value in group:
  print(key,list(value))

20 [{'name': 'tina', 'age': 20}, {'name': 'mina', 'age': 20}]
12 [{'name': 'dika', 'age': 12}]


In [ ]:
### infinite iterators---- count,repeat,cycle

20

# Lambda function

In [ ]:
add10=lambda x: x+10
add10(88)

98

In [ ]:
# multiple arguments

mul=lambda x,y: x*y
mul(22,2)

44

In [ ]:
# lamda with sorted function
point2d=[(1,4),(2,-1),(0,0),(3,4)]
# sorting with out lamda

point2d_s=sorted(point2d)
print(point2d)
print(point2d_s)

# sorting on the y coordinate
point2d_s=sorted(point2d, key=lambda x:x[1])
print(point2d_s)

[(1, 4), (2, -1), (0, 0), (3, 4)]
[(0, 0), (1, 4), (2, -1), (3, 4)]
[(2, -1), (0, 0), (1, 4), (3, 4)]


In [ ]:
def sort(x):
  return x[1]
sort(point2d)

(2, -1)

#### using lambda with map function

In [ ]:
l1=[1,2,3,4,5,6,7,8]
l2=map(lambda x: x*2, l1)
print(list(l2))

[2, 4, 6, 8, 10, 12, 14, 16]


In [ ]:
# results with list comprehension
l2=[x*2 for x in l1]
l2

[2, 4, 6, 8, 10, 12, 14, 16]

In [ ]:
# lambda w filter function

l2=filter(lambda x: x%2==0, l1)
print(list(l2))

[2, 4, 6, 8]


# Exceptions in Python
##### There are syntactical error(problem in syntax)
and exceptional errors.
some built in exception error: typeError, modulenotfoundError, nameError, fileError etc

#### Raising an exception

In [ ]:
x=-5
if x <0:
  raise Exception("Be Positive")

Exception: ignored

#### Assertion Error

In [ ]:
x=-5
assert(x>=0), 'Be Positive'

AssertionError: ignored

In [ ]:
try:
 a=5/0
except:
  print('an error occured')

an error occured


#### to catch the type of exception

In [ ]:
try:
 a=5/0
except Exception as e:
  print(e)

division by zero


In [ ]:
try:
  b=5+'s'
  a=5/1
except TypeError as e:
  print(e)
except ZeroDivisionError as e:
  print(e)
finally:
  print("always gets printed no matter what")

try:
    b=5+5
    a=5/0
except TypeError as e:
  print(e)
except ZeroDivisionError as e:
  print(e)
finally:
  print("always gets printed no matter what")

try:
    b=5+5
    a=5/1
except TypeError as e:
  print(e)
except ZeroDivisionError as e:
  print(e)
else:
  print("seems just good")
finally:
  print("always gets printed no matter what")

unsupported operand type(s) for +: 'int' and 'str'
always gets printed no matter what
division by zero
always gets printed no matter what
seems just good
always gets printed no matter what


### Defining our own exceptions

In [ ]:
class ValueHighError(Exception):
  pass

def test_value(x):
  if x>100:
    raise ValueHighError('Value too high')

test_value(200)

ValueHighError: ignored

In [ ]:
class ValueHighError(Exception):
  pass

def test_value(x):
   if x>100:
    raise ValueHighError('Value too high')


try :
    test_value(200)
except ValueHighError as e:
    print(e)

Value too high


In [ ]:
class ValueLowError(Exception):
  def __init__(self,message,value):
    self.message=message
    self.value=value
def test_value(x):
    if x<5:
      raise ValueLowError('Value too low',x)

try:
  test_value(1)
except ValueLowError as e:
  print(e.message,e.value)


Value too low 1


# converting a python dictionary into a json object

In [ ]:
import json
person = {"name": "John", "age": 30, "city": "New York", "hasChildren": False, "titles": ["engineer", "programmer"]}

person_json=json.dumps(person)
print(person_json)
# converting back to python dictionaries

person=json.loads(person_json)
print(person)

{"name": "John", "age": 30, "city": "New York", "hasChildren": false, "titles": ["engineer", "programmer"]}
{'name': 'John', 'age': 30, 'city': 'New York', 'hasChildren': False, 'titles': ['engineer', 'programmer']}


# Random Numbers

In [ ]:
import random
a=random.random()
a

0.15299113740624026

In [ ]:
a=random.uniform(1,10)
a

4.436882507151353

In [ ]:
a=random.randint(1,10)
a

9

In [ ]:
a=random.randrange(1,10)  #upper bound is not included
a

9

In [ ]:
a=random.normalvariate(0,1)  # where 1 is the std deviation and 0 is the mean
a

0.9054027501590254

#### importing random elements from the list

In [ ]:
li=list("ABCDEFGHI")
print(li)
choice=random.choice(li)
choice

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']


'G'

In [ ]:
choice=random.sample(li,4)
choice

['I', 'H', 'A', 'F']

In [ ]:
random.shuffle(li)

In [ ]:
li

['C', 'I', 'F', 'D', 'B', 'H', 'E', 'G', 'A']

#### Reproducing data with random seed function

In [ ]:
random.seed(1)
print(random.random())

random.seed(2)
print(random.random())

0.13436424411240122
0.9560342718892494


In [ ]:
random.seed(1)
print(random.random())

0.13436424411240122


In [ ]:
import secrets #has only three functions, good for security
print(secrets.randbits(4))

6


## numpy

In [ ]:
import numpy as np
a=np.random.rand(3,2)
a

array([[0.64493925, 0.80382493],
       [0.06451118, 0.71956891],
       [0.83119236, 0.65634573]])

In [ ]:
a=np.random.randint(1,10,(3,4))
a

array([[7, 2, 7, 8],
       [2, 5, 6, 9],
       [2, 8, 1, 8]])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.shape

(3, 3)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

2

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
np.random.seed(1)
print(np.random.randint(3,14,(3,3)))

[[ 8 11 12]
 [ 8  3  3]
 [ 4 10  9]]


# Decorators in Python

there are two types of decorators 1. class decorator 2. function decorator

-- extends the behaviour of the function with decorator

In [ ]:
def start_end(func):
  def wrapper():
    print("Start")
    func()
    print('End')
  return wrapper

def print_name():
  print("Alex")

print_=start_end(print_name)
print_()


Start
Alex
End


In [ ]:
def start_end(func):
  def wrapper():
    print("Start")
    func()
    print('End')
  return wrapper


@start_end
def print_name():
  print("Alex")

print_name()



Start
Alex
End


In [ ]:
def start_end(func):
    print("Start")
    func()
    print('End')
  


@start_end
def print_name():
  print("Alex")



Start
Alex
End


In [ ]:
def start_end(func):
  def wrapper(*args,**kwargs):
    print("Start")
    result=func(*args,**kwargs)
    print('End')
    return result
  return wrapper


@start_end
def print_name(x):
  return x+10

result=print_name(12)
result

Start
End


22

### make a decorator to repeat a function n times

In [ ]:
import functools
def repeat(n):
  def repeat_decorator(func):
     
     @functools.wraps(func)
     def wrapper(*args,**kwargs):
       for _ in range(n):
         result=func(*args,**kwargs)
       return result
     return wrapper
  return repeat_decorator


@repeat(n=3)
def greet(name):
  print(f'Hello {name}')

greet('Ushna')

Hello Ushna
Hello Ushna
Hello Ushna


### Nested Decorators

In [ ]:
def debug(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args_repr = [repr(a) for a in args]
        kwargs_repr = [f"{k}={v!r}" for k, v in kwargs.items()]
        signature = ", ".join(args_repr + kwargs_repr)
        print(f"Calling {func.__name__}({signature})")
        result = func(*args, **kwargs)
        print(f"{func.__name__!r} returned {result!r}")
        return result
    return wrapper

def start_end_decorator_4(func):
    
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print('Start')
        result = func(*args, **kwargs)
        print('End')
        return result
    return wrapper

@debug
@start_end_decorator_4
def say_hello(name):
    greeting = f'Hello {name}'
    print(greeting)
    return greeting

# now `debug` is executed first and calls `@start_end_decorator_4`, which then calls `say_hello`
say_hello(name='Alex')

Calling say_hello(name='Alex')
Start
Hello Alex
End
'say_hello' returned 'Hello Alex'


'Hello Alex'

## Class Decorators

In [ ]:

class CountCalls:
    # the init needs to have the func as argument and stores it
    def __init__(self, func):
        functools.update_wrapper(self, func)
        self.func = func
        self.num_calls = 0
    
    # extend functionality, execute function, and return the result
    def __call__(self, *args, **kwargs):
        self.num_calls += 1
        print(f"Call {self.num_calls} of {self.func.__name__!r}")
        return self.func(*args, **kwargs)

@CountCalls
def say_hello(num):
    print("Hello!")
    
say_hello(5)
say_hello(5)

Call 1 of 'say_hello'
Hello!
Call 2 of 'say_hello'
Hello!


## Some typical use cases
Use a timer decorator to calculate the execution time of a function
Use a debug decorator to print out some more information about the called function and its arguments
Use a check decorator to check if the arguments fulfill some requirements and adapt the bevaviour accordingly
Register functions (plugins)
Slow down code with time.sleep() to check network behaviour
Cache the return values for memoization (https://en.wikipedia.org/wiki/Memoization)
Add information or update a state

# Generators

In [ ]:
def mygenerators():
  yield 1
  yield 2
  yield 3

g=mygenerators()

for i in g:
  print(i)



1
2
3


In [ ]:
def mygenerators():
  yield 1
  yield 2
  yield 3

g=mygenerators()
sorted(g)

[1, 2, 3]

In [ ]:
g=mygenerators()
sum(g)

6

In [ ]:
def countdown(num):
  print('Starting')
  while num>=0:
    yield num
    num -=1

c=countdown(4)
value=next(c)
print(next(c))

Starting
3


In [ ]:
print(next(c))

1


In [ ]:
def first_n(n):
  num=0
  nums=[]
  while num<n:
    nums.append(num)
    num +=1
  return nums

print(sum(first_n(22)))

231


In [ ]:
### generators are memory efficient

def first_n_generators(n):
  num=0
  while num<n:
    yield num
    num +=1

print(sum(first_n_generators(22)))

231


In [ ]:
import sys
def first_n(n):
  num=0
  nums=[]
  while num<n:
    nums.append(num)
    num +=1
  return nums



def first_n_generators(n):
  num=0
  while num<n:
    yield num
    num +=1


print(sys.getsizeof(first_n(1000000)))
print(sys.getsizeof(first_n_generators(100000)))


8697472
128


In [ ]:
# without a generator, the complete sequence has to be stored here in a list
def firstn(n):
    num, nums = 0, []
    while num < n:
        nums.append(num)
        num += 1
    return nums

sum_of_first_n = sum(firstn(1000000))
print(sum_of_first_n)

print(sys.getsizeof(firstn(100000)), "bytes")

# with a generator, no additional sequence is needed to store the numbers
def firstn(n):
    num = 0
    while num < n:
        yield num
        num += 1

sum_of_first_n = sum(firstn(10000))
print(sum_of_first_n)

print(sys.getsizeof(firstn(1000000)), "bytes")

499999500000
824472 bytes
49995000
128 bytes


In [ ]:
def fibonacci(limit):
  a,b=0,1
  while a< limit:
    yield a
    a,b=b,a+b

fib=fibonacci(6)
for i in fib:
  print(i)

0
1
1
2
3
5


In [ ]:
mygenerator=(i for i in range(10) if i%2==0)
print(list(mygenerator))

[0, 2, 4, 6, 8]


In [ ]:
a=5
b=10
a,b=b,a+b
print(a,b)

10 15


# Multiprocessing in Python

In [ ]:
from multiprocessing import Process
import time

In [ ]:
result=[]
def greet(name):
  for i in range(5):
    print(f'Hello {name}')
    time.sleep(1)

def calc_square(n):
  global result
  for i in range(n):
    time.sleep(1)
    print(i*i)
    result.append(i*i)
  print(result)
    

p1=Process(target=greet,args=('Ushna',))
p2=Process(target=calc_square,args=(5,))

p1.start()
p2.start()

p1.join()
p2.join()

print(result)
print("End")

Hello Ushna
0
Hello Ushna
1
Hello Ushna
4
Hello Ushna
9
Hello Ushna
16
[0, 1, 4, 9, 16]
[]
End


In [ ]:
import os
os.cpu_count()

2

# Multithreading in Python

In [ ]:
def squares(arr):
  print("Squares:")
  for i in arr:
    print(f'{i}: {i*i}')
    time.sleep(0.2)

def cubes(arr):
  print("Cubes:")
  for i in arr:
    print(f'{i}: {i*i*i}')
    time.sleep(0.2)


t=time.time()
print(t)
array=[2,4,6,7]
squares(array)
cubes(array)


print(f'I took {(time.time()-t)} to execute')

1659078010.7993555
Squares:
2: 4
4: 16
6: 36
7: 49
Cubes:
2: 8
4: 64
6: 216
7: 343
I took 1.6079130172729492 to execute


In [ ]:
t=time.time()
print(t)

1659078052.7136216


In [ ]:
help(time)

### Let's reduce the time with multithreading

In [ ]:
import threading

t=time.time()

array=[2,4,6,7]
t1=threading.Thread(target=squares,args=(array,))
t2=threading.Thread(target=cubes,args=(array,))

t1.start()
t2.start()

t1.join()
t2.join()

print(f'I took {(time.time()-t)} to execute')


Squares:Cubes:

2: 8
2: 4
4: 644: 16

6: 36
6: 216
7: 343
7: 49
I took 0.8086469173431396 to execute


# Sharing data between processes
In the above(process code) the global variable result did not have any value when we tried to printed it from main, but when we printed it from the function it got printed, it is simply because the process created a copy of the result and stored values in it. Resolving the issue next:


#### Data can be shared using arrays, values, queue, pipes

In [ ]:
import multiprocessing
def squares(array,result):
  for idx, i in enumerate(array):
    result[idx]=i*i
 
array=[2,3,4]
result=multiprocessing.Array('i',3)

t=time.time()
p=multiprocessing.Process(target=squares,args=(array,result))

p.start()
p.join()

print(result[:])
print(time.time()-t)

[4, 9, 16]
0.014040946960449219


ps: different processes have different address spaces

# Multiprocessing lock
when ever two threads or processes try to access a shared memory we need a lock

In [ ]:
def deposit(balance, lock):
    for i in range(100):
        time.sleep(0.01)
        lock.acquire()
        balance.value = balance.value + 1
        lock.release()

def withdraw(balance, lock):
    for i in range(100):
        time.sleep(0.01)
        lock.acquire()
        balance.value = balance.value - 1
        lock.release()

if __name__ == '__main__':
    balance = multiprocessing.Value('i', 200)
    lock = multiprocessing.Lock()
    d = multiprocessing.Process(target=deposit, args=(balance,lock))
    w = multiprocessing.Process(target=withdraw, args=(balance,lock))
    d.start()
    w.start()
    d.join()
    w.join()
    print(balance.value)

200
